import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '../components/layout/Header';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

import { dbConnect } from '@/features/lib/db';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const conn = await dbConnect();
  return (
    <html lang='en' className='bg-main-50'>
      <body className={inter.className + ' m-auto container'}>
        <Header />
        {children}
      </body>
    </html>
  );
}
